# Табличные данные

**Цель**:

**Требования к отчету (реализовано):**

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/covtype.csv') # default delimiter is ','
df.head() # default is 5

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,2596,51,3,258,0,510,221,232,148,6279,...,0,0,0,0,0,0,0,0,0,5
1,2590,56,2,212,-6,390,220,235,151,6225,...,0,0,0,0,0,0,0,0,0,5
2,2804,139,9,268,65,3180,234,238,135,6121,...,0,0,0,0,0,0,0,0,0,2
3,2785,155,18,242,118,3090,238,238,122,6211,...,0,0,0,0,0,0,0,0,0,2
4,2595,45,2,153,-1,391,220,234,150,6172,...,0,0,0,0,0,0,0,0,0,5

In [3]:
print(df.shape)

(581012, 55)

In [4]:
print(df.dtypes)

Elevation                             int64
Aspect                                int64
Slope                                 int64
Horizontal_Distance_To_Hydrology      int64
Vertical_Distance_To_Hydrology        int64
Horizontal_Distance_To_Roadways       int64
Hillshade_9am                         int64
Hillshade_Noon                        int64
Hillshade_3pm                         int64
Horizontal_Distance_To_Fire_Points    int64
Wilderness_Area1                      int64
Wilderness_Area2                      int64
Wilderness_Area3                      int64
Wilderness_Area4                      int64
Soil_Type1                            int64
Soil_Type2                            int64
Soil_Type3                            int64
Soil_Type4                            int64
Soil_Type5                            int64
Soil_Type6                            int64
Soil_Type7                            int64
Soil_Type8                            int64
Soil_Type9                            int64
Soil_Type10                           int64
Soil_Type11                           int64
Soil_Type12                           int64
Soil_Type13                           int64
Soil_Type14                           int64
Soil_Type15                           int64
Soil_Type16                           int64
Soil_Type17                           int64
Soil_Type18                           int64
Soil_Type19                           int64
Soil_Type20                           int64
Soil_Type21                           int64
Soil_Type22                           int64
Soil_Type23                           int64
Soil_Type24                           int64
Soil_Type25                           int64
Soil_Type26                           int64
Soil_Type27                           int64
Soil_Type28                           int64
Soil_Type29                           int64
Soil_Type30                           int64
Soil_Type31                           int64
Soil_Type32                           int64
Soil_Type33                           int64
Soil_Type34                           int64
Soil_Type35                           int64
Soil_Type36                           int64
Soil_Type37                           int64
Soil_Type38                           int64
Soil_Type39                           int64
Soil_Type40                           int64
Cover_Type                            int64
dtype: object

In [5]:
print(type(df.values)) # ? вывод типов данных;

<class 'numpy.ndarray'>

In [6]:
# TODO: какие столбцы являются числовыми, а какие категориальными.

In [7]:
print(f'Max:\n{df.max()}')
print(f'Min:\n{df.min()}')

Max:
Elevation                             3858
Aspect                                 360
Slope                                   66
Horizontal_Distance_To_Hydrology      1397
Vertical_Distance_To_Hydrology         601
Horizontal_Distance_To_Roadways       7117
Hillshade_9am                          254
Hillshade_Noon                         254
Hillshade_3pm                          254
Horizontal_Distance_To_Fire_Points    7173
Wilderness_Area1                         1
Wilderness_Area2                         1
Wilderness_Area3                         1
Wilderness_Area4                         1
Soil_Type1                               1
Soil_Type2                               1
Soil_Type3                               1
Soil_Type4                               1
Soil_Type5                               1
Soil_Type6                               1
Soil_Type7                               1
Soil_Type8                               1
Soil_Type9                               1
Soil_Type10                              1
Soil_Type11                              1
Soil_Type12                              1
Soil_Type13                              1
Soil_Type14                              1
Soil_Type15                              1
Soil_Type16                              1
Soil_Type17                              1
Soil_Type18                              1
Soil_Type19                              1
Soil_Type20                              1
Soil_Type21                              1
Soil_Type22                              1
Soil_Type23                              1
Soil_Type24                              1
Soil_Type25                              1
Soil_Type26                              1
Soil_Type27                              1
Soil_Type28                              1
Soil_Type29                              1
Soil_Type30                              1
Soil_Type31                              1
Soil_Type32                              1
Soil_Type33                              1
Soil_Type34                              1
Soil_Type35                              1
Soil_Type36                              1
Soil_Type37                              1
Soil_Type38                              1
Soil_Type39                              1
Soil_Type40                              1
Cover_Type                               7
dtype: int64
Min:
Elevation                             1859
Aspect                                   0
Slope                                    0
Horizontal_Distance_To_Hydrology         0
Vertical_Distance_To_Hydrology        -173
Horizontal_Distance_To_Roadways          0
Hillshade_9am                            0
Hillshade_Noon                           0
Hillshade_3pm                            0
Horizontal_Distance_To_Fire_Points       0
Wilderness_Area1                         0
Wilderness_Area2                         0
Wilderness_Area3                         0
Wilderness_Area4                         0
Soil_Type1                               0
Soil_Type2                               0
Soil_Type3                               0
Soil_Type4                               0
Soil_Type5                               0
Soil_Type6                               0
Soil_Type7                               0
Soil_Type8                               0
Soil_Type9                               0
Soil_Type10                              0
Soil_Type11                              0
Soil_Type12                              0
Soil_Type13                              0
Soil_Type14                              0
Soil_Type15                              0
Soil_Type16                              0
Soil_Type17                              0
Soil_Type18                              0
Soil_Type19                              0
Soil_Type20                              0
Soil_Type21                              0
Soil_Type22                              0
Soil_Type23                              0
Soil_Type24                              0
Soil_Type25                              0
Soil_Type26                              0
Soil_Type27                              0
Soil_Type28                              0
Soil_Type29                              0
Soil_Type30                              0
Soil_Type31                              0
Soil_Type32                              0
Soil_Type33                              0
Soil_Type34                              0
Soil_Type35                              0
Soil_Type36                              0
Soil_Type37                              0
Soil_Type38                              0
Soil_Type39                              0
Soil_Type40                              0
Cover_Type                               1
dtype: int64

In [8]:
print(f'Mean:\n{df.mean()}')

Mean:
Elevation                             2959.365301
Aspect                                 155.656807
Slope                                   14.103704
Horizontal_Distance_To_Hydrology       269.428217
Vertical_Distance_To_Hydrology          46.418855
Horizontal_Distance_To_Roadways       2350.146611
Hillshade_9am                          212.146049
Hillshade_Noon                         223.318716
Hillshade_3pm                          142.528263
Horizontal_Distance_To_Fire_Points    1980.291226
Wilderness_Area1                         0.448865
Wilderness_Area2                         0.051434
Wilderness_Area3                         0.436074
Wilderness_Area4                         0.063627
Soil_Type1                               0.005217
Soil_Type2                               0.012952
Soil_Type3                               0.008301
Soil_Type4                               0.021335
Soil_Type5                               0.002749
Soil_Type6                               0.011316
Soil_Type7                               0.000181
Soil_Type8                               0.000308
Soil_Type9                               0.001974
Soil_Type10                              0.056168
Soil_Type11                              0.021359
Soil_Type12                              0.051584
Soil_Type13                              0.030001
Soil_Type14                              0.001031
Soil_Type15                              0.000005
Soil_Type16                              0.004897
Soil_Type17                              0.005890
Soil_Type18                              0.003268
Soil_Type19                              0.006921
Soil_Type20                              0.015936
Soil_Type21                              0.001442
Soil_Type22                              0.057439
Soil_Type23                              0.099399
Soil_Type24                              0.036622
Soil_Type25                              0.000816
Soil_Type26                              0.004456
Soil_Type27                              0.001869
Soil_Type28                              0.001628
Soil_Type29                              0.198356
Soil_Type30                              0.051927
Soil_Type31                              0.044175
Soil_Type32                              0.090392
Soil_Type33                              0.077716
Soil_Type34                              0.002773
Soil_Type35                              0.003255
Soil_Type36                              0.000205
Soil_Type37                              0.000513
Soil_Type38                              0.026803
Soil_Type39                              0.023762
Soil_Type40                              0.015060
Cover_Type                               2.051471
dtype: float64

In [9]:
# TODO: признаки с наибольшим разбросом.

Выполните фильтрацию данных по одному условию (например, значение признака больше/меньше заданного).

In [23]:
CONDITION_NUMBER = 250
df_filtered = df[df['Hillshade_3pm'] > CONDITION_NUMBER]
df_filtered

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
229337,2719,271,42,509,236,912,80,213,251,1741,...,0,0,0,0,0,0,0,0,0,2
325592,3355,274,44,162,65,3360,72,207,251,1727,...,0,0,0,0,0,0,0,1,0,1
326286,3355,268,43,134,49,3372,79,214,251,1697,...,0,0,0,0,0,0,0,1,0,1
352621,2836,268,43,300,202,1358,81,215,251,1482,...,0,0,0,0,0,0,0,0,0,2
353237,2804,264,44,270,170,1358,79,215,251,1443,...,0,0,0,0,0,0,0,0,0,2
353238,2833,266,44,300,199,1379,76,213,252,1471,...,0,0,0,0,0,0,0,0,0,2
353242,2913,265,42,420,279,1465,83,217,251,1584,...,0,1,0,0,0,0,0,0,0,2
353855,2801,269,45,270,167,1380,71,209,252,1433,...,0,0,0,0,0,0,0,0,0,2
353856,2833,271,45,300,199,1401,70,208,252,1461,...,0,0,0,0,0,0,0,0,0,2
353860,2907,268,44,420,273,1486,73,211,252,1575,...,0,1,0,0,0,0,0,0,0,2
354465,2801,272,47,270,167,1403,61,202,253,1423,...,0,0,0,0,0,0,0,0,0,2
354466,2836,275,46,300,202,1423,64,202,252,1452,...,0,0,0,0,0,0,0,0,0,2
355074,2772,272,45,240,138,1406,67,205,253,1385,...,0,0,0,0,0,0,0,0,0,2
355075,2804,276,48,270,170,1425,53,195,253,1414,...,0,0,0,0,0,0,0,0,0,2
355076,2839,276,45,300,205,1445,64,201,252,1442,...,0,0,0,0,0,0,0,0,0,2
355674,2741,264,44,210,103,1410,78,215,251,1348,...,0,0,0,0,0,0,0,0,0,2
355675,2775,267,48,240,141,1429,60,204,254,1376,...,0,0,0,0,0,0,0,0,0,2
355676,2810,269,48,270,176,1448,56,201,254,1405,...,0,0,0,0,0,0,0,0,0,2
355677,2843,268,44,300,209,1468,74,211,252,1434,...,0,0,0,0,0,0,0,0,0,2
356284,2738,269,44,210,104,1434,72,210,252,1339,...,0,0,0,0,0,0,0,0,0,2
356285,2769,266,47,240,131,1452,64,207,253,1368,...,0,0,0,0,0,0,0,0,0,2
356286,2804,260,47,270,170,1471,68,211,252,1397,...,0,0,0,0,0,0,0,0,0,2
356903,2741,274,45,210,100,1458,66,204,252,1332,...,0,0,0,0,0,0,0,0,0,2
356904,2772,276,46,240,138,1476,63,201,252,1361,...,0,0,0,0,0,0,0,0,0,2
356905,2797,274,44,270,159,1495,70,206,252,1390,...,0,0,0,0,0,0,0,0,0,2
356906,2826,270,44,300,192,1513,72,209,252,1419,...,0,0,0,0,0,0,0,0,0,2
356907,2859,267,42,330,225,1533,84,217,251,1448,...,0,0,0,0,0,0,0,0,0,2
357521,2741,273,48,210,97,1482,54,197,253,1324,...,0,0,0,0,0,0,0,0,0,2
357522,2778,279,47,240,137,1500,56,194,251,1354,...,0,0,0,0,0,0,0,0,0,2
358142,2711,276,43,180,73,1489,73,206,251,1289,...,0,0,0,0,0,0,0,0,0,2
358143,2744,276,50,210,100,1507,46,191,253,1318,...,0,0,0,0,0,0,0,0,0,2
358144,2785,274,47,240,141,1524,60,200,253,1347,...,0,0,0,0,0,0,0,0,0,2
358755,2751,274,47,210,113,1531,57,198,253,1312,...,0,0,0,0,0,0,0,0,0,2
358756,2782,266,44,240,138,1548,78,214,252,1342,...,0,0,0,0,0,0,0,0,0,2
359353,2751,271,43,210,110,1556,75,210,252,1307,...,0,0,0,0,0,0,0,0,0,2
391119,2922,279,47,60,22,2491,0,194,252,792,...,0,0,0,0,0,0,0,0,0,1
391753,2918,273,50,90,25,2496,0,192,254,780,...,0,0,0,0,0,0,0,0,0,1
392384,2925,275,50,120,32,2501,0,191,254,769,...,0,0,0,0,0,0,0,0,0,1
572174,2782,260,45,365,148,3115,78,216,251,1537,...,0,0,0,0,0,0,0,0,0,3

Отсортируйте отфильтрованные данные: по возрастанию

In [24]:
df_filtered.sort_values('Hillshade_3pm')

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
229337,2719,271,42,509,236,912,80,213,251,1741,...,0,0,0,0,0,0,0,0,0,2
325592,3355,274,44,162,65,3360,72,207,251,1727,...,0,0,0,0,0,0,0,1,0,1
326286,3355,268,43,134,49,3372,79,214,251,1697,...,0,0,0,0,0,0,0,1,0,1
352621,2836,268,43,300,202,1358,81,215,251,1482,...,0,0,0,0,0,0,0,0,0,2
353237,2804,264,44,270,170,1358,79,215,251,1443,...,0,0,0,0,0,0,0,0,0,2
353242,2913,265,42,420,279,1465,83,217,251,1584,...,0,1,0,0,0,0,0,0,0,2
355674,2741,264,44,210,103,1410,78,215,251,1348,...,0,0,0,0,0,0,0,0,0,2
357522,2778,279,47,240,137,1500,56,194,251,1354,...,0,0,0,0,0,0,0,0,0,2
358142,2711,276,43,180,73,1489,73,206,251,1289,...,0,0,0,0,0,0,0,0,0,2
356907,2859,267,42,330,225,1533,84,217,251,1448,...,0,0,0,0,0,0,0,0,0,2
572174,2782,260,45,365,148,3115,78,216,251,1537,...,0,0,0,0,0,0,0,0,0,3
353855,2801,269,45,270,167,1380,71,209,252,1433,...,0,0,0,0,0,0,0,0,0,2
355076,2839,276,45,300,205,1445,64,201,252,1442,...,0,0,0,0,0,0,0,0,0,2
353856,2833,271,45,300,199,1401,70,208,252,1461,...,0,0,0,0,0,0,0,0,0,2
354466,2836,275,46,300,202,1423,64,202,252,1452,...,0,0,0,0,0,0,0,0,0,2
353860,2907,268,44,420,273,1486,73,211,252,1575,...,0,1,0,0,0,0,0,0,0,2
356906,2826,270,44,300,192,1513,72,209,252,1419,...,0,0,0,0,0,0,0,0,0,2
356905,2797,274,44,270,159,1495,70,206,252,1390,...,0,0,0,0,0,0,0,0,0,2
356903,2741,274,45,210,100,1458,66,204,252,1332,...,0,0,0,0,0,0,0,0,0,2
356284,2738,269,44,210,104,1434,72,210,252,1339,...,0,0,0,0,0,0,0,0,0,2
356904,2772,276,46,240,138,1476,63,201,252,1361,...,0,0,0,0,0,0,0,0,0,2
355677,2843,268,44,300,209,1468,74,211,252,1434,...,0,0,0,0,0,0,0,0,0,2
356286,2804,260,47,270,170,1471,68,211,252,1397,...,0,0,0,0,0,0,0,0,0,2
353238,2833,266,44,300,199,1379,76,213,252,1471,...,0,0,0,0,0,0,0,0,0,2
359353,2751,271,43,210,110,1556,75,210,252,1307,...,0,0,0,0,0,0,0,0,0,2
391119,2922,279,47,60,22,2491,0,194,252,792,...,0,0,0,0,0,0,0,0,0,1
358756,2782,266,44,240,138,1548,78,214,252,1342,...,0,0,0,0,0,0,0,0,0,2
357521,2741,273,48,210,97,1482,54,197,253,1324,...,0,0,0,0,0,0,0,0,0,2
355074,2772,272,45,240,138,1406,67,205,253,1385,...,0,0,0,0,0,0,0,0,0,2
355075,2804,276,48,270,170,1425,53,195,253,1414,...,0,0,0,0,0,0,0,0,0,2
356285,2769,266,47,240,131,1452,64,207,253,1368,...,0,0,0,0,0,0,0,0,0,2
354465,2801,272,47,270,167,1403,61,202,253,1423,...,0,0,0,0,0,0,0,0,0,2
358755,2751,274,47,210,113,1531,57,198,253,1312,...,0,0,0,0,0,0,0,0,0,2
358143,2744,276,50,210,100,1507,46,191,253,1318,...,0,0,0,0,0,0,0,0,0,2
358144,2785,274,47,240,141,1524,60,200,253,1347,...,0,0,0,0,0,0,0,0,0,2
355676,2810,269,48,270,176,1448,56,201,254,1405,...,0,0,0,0,0,0,0,0,0,2
355675,2775,267,48,240,141,1429,60,204,254,1376,...,0,0,0,0,0,0,0,0,0,2
391753,2918,273,50,90,25,2496,0,192,254,780,...,0,0,0,0,0,0,0,0,0,1
392384,2925,275,50,120,32,2501,0,191,254,769,...,0,0,0,0,0,0,0,0,0,1

Отсортируйте отфильтрованные данные: по убыванию

In [25]:
df_filtered.sort_values('Hillshade_3pm', ascending=False)

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
392384,2925,275,50,120,32,2501,0,191,254,769,...,0,0,0,0,0,0,0,0,0,1
355675,2775,267,48,240,141,1429,60,204,254,1376,...,0,0,0,0,0,0,0,0,0,2
355676,2810,269,48,270,176,1448,56,201,254,1405,...,0,0,0,0,0,0,0,0,0,2
391753,2918,273,50,90,25,2496,0,192,254,780,...,0,0,0,0,0,0,0,0,0,1
354465,2801,272,47,270,167,1403,61,202,253,1423,...,0,0,0,0,0,0,0,0,0,2
356285,2769,266,47,240,131,1452,64,207,253,1368,...,0,0,0,0,0,0,0,0,0,2
355075,2804,276,48,270,170,1425,53,195,253,1414,...,0,0,0,0,0,0,0,0,0,2
357521,2741,273,48,210,97,1482,54,197,253,1324,...,0,0,0,0,0,0,0,0,0,2
358143,2744,276,50,210,100,1507,46,191,253,1318,...,0,0,0,0,0,0,0,0,0,2
358144,2785,274,47,240,141,1524,60,200,253,1347,...,0,0,0,0,0,0,0,0,0,2
358755,2751,274,47,210,113,1531,57,198,253,1312,...,0,0,0,0,0,0,0,0,0,2
355074,2772,272,45,240,138,1406,67,205,253,1385,...,0,0,0,0,0,0,0,0,0,2
355677,2843,268,44,300,209,1468,74,211,252,1434,...,0,0,0,0,0,0,0,0,0,2
353238,2833,266,44,300,199,1379,76,213,252,1471,...,0,0,0,0,0,0,0,0,0,2
353856,2833,271,45,300,199,1401,70,208,252,1461,...,0,0,0,0,0,0,0,0,0,2
359353,2751,271,43,210,110,1556,75,210,252,1307,...,0,0,0,0,0,0,0,0,0,2
356903,2741,274,45,210,100,1458,66,204,252,1332,...,0,0,0,0,0,0,0,0,0,2
356284,2738,269,44,210,104,1434,72,210,252,1339,...,0,0,0,0,0,0,0,0,0,2
356286,2804,260,47,270,170,1471,68,211,252,1397,...,0,0,0,0,0,0,0,0,0,2
355076,2839,276,45,300,205,1445,64,201,252,1442,...,0,0,0,0,0,0,0,0,0,2
354466,2836,275,46,300,202,1423,64,202,252,1452,...,0,0,0,0,0,0,0,0,0,2
353860,2907,268,44,420,273,1486,73,211,252,1575,...,0,1,0,0,0,0,0,0,0,2
353855,2801,269,45,270,167,1380,71,209,252,1433,...,0,0,0,0,0,0,0,0,0,2
391119,2922,279,47,60,22,2491,0,194,252,792,...,0,0,0,0,0,0,0,0,0,1
358756,2782,266,44,240,138,1548,78,214,252,1342,...,0,0,0,0,0,0,0,0,0,2
356906,2826,270,44,300,192,1513,72,209,252,1419,...,0,0,0,0,0,0,0,0,0,2
356905,2797,274,44,270,159,1495,70,206,252,1390,...,0,0,0,0,0,0,0,0,0,2
356904,2772,276,46,240,138,1476,63,201,252,1361,...,0,0,0,0,0,0,0,0,0,2
325592,3355,274,44,162,65,3360,72,207,251,1727,...,0,0,0,0,0,0,0,1,0,1
229337,2719,271,42,509,236,912,80,213,251,1741,...,0,0,0,0,0,0,0,0,0,2
326286,3355,268,43,134,49,3372,79,214,251,1697,...,0,0,0,0,0,0,0,1,0,1
353242,2913,265,42,420,279,1465,83,217,251,1584,...,0,1,0,0,0,0,0,0,0,2
353237,2804,264,44,270,170,1358,79,215,251,1443,...,0,0,0,0,0,0,0,0,0,2
352621,2836,268,43,300,202,1358,81,215,251,1482,...,0,0,0,0,0,0,0,0,0,2
355674,2741,264,44,210,103,1410,78,215,251,1348,...,0,0,0,0,0,0,0,0,0,2
358142,2711,276,43,180,73,1489,73,206,251,1289,...,0,0,0,0,0,0,0,0,0,2
357522,2778,279,47,240,137,1500,56,194,251,1354,...,0,0,0,0,0,0,0,0,0,2
356907,2859,267,42,330,225,1533,84,217,251,1448,...,0,0,0,0,0,0,0,0,0,2
572174,2782,260,45,365,148,3115,78,216,251,1537,...,0,0,0,0,0,0,0,0,0,3